# Generated by Django 6.0.6 on 2026-07-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/')),
                ('title', models.CharField(max_length=150)),
                ('property_type', models.CharField(choices=[('APARTMENT', 'Apartment'), ('VILLA', 'Villa'), ('PENTHOUSE', 'Penthouse'), ('PLOT', 'Plot'), ('OFFICE', 'Office'), ('SHOP', 'Shop')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('area_sqft', models.PositiveIntegerField(help_text='Area in square feet')),
                ('is_rera_compliant', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
